10.	2D convolution


clc;
clear all;
close all;
f=imread(‘ultrasound_liver.jpg’);
g1=imcomlement(f);
g2=imcomlement(f);
g3=ones(size(f));
o1=conv2(f,g1,’same’);
o2=conv2(f,g2,’same’);
o1=conv2(f,g3,’same’);
subplot(4,3,1);
imshow(f);
title(‘input image’);
subplot(4,3,2);
imshow(g1);
title(‘mask 1’);
subplot(4,3,3);
imshow(g2);
title(‘mask 2’);
subplot(4,3,4);
imshow(g3);
title(‘mask 3’);
subplot(4,3,5);
imshow(o1);
title(‘o1=f*g1’);
subplot(4,3,6);
imshow(o2);
title(‘o2=f*g2’);
subplot(4,3,7);
imshow(o3);
title(‘o3=f*g3’);
subplot(4,3,8);
imhist(f);
title(‘histogram of f’);
subplot(4,3,9);
imhist(o1);
title(‘histogram of o1’);
subplot(4,3,10);
imhist(o2);
title(‘histogram of o2’);
subplot(4,3,11);
imhist(o3);
title(‘histogram of o3’);
mean of input=mean2(f);
mean of o1=mean2(o1);
mean of o2=mean2(o2);
mean of o3=mean2(o3);
