Clc ; 
clear all; 
close all;
i=imread(‘ultrasound fetus.jpg’);
subplot(2,2,1);
imshow(i);
title(‘original image’);
n=imnoise(i,’salt & pepper’);
subplot(2,2,2);
imshow(n);
title(‘noisy image’);
f1=fspecial(‘average’);
Ip=imfilter(n,f1);
subplot(2,2,3);
imshow(Ip);
title(‘Mean filtered image’);
m=medfilt2(n);
subplot(2,2,4);
imshow(m);
title(‘Median filtered image’);
